const Characters = [
  {
    id: 1,
    charName: 'Evil Bob',
    picture: 'https://oldschool.runescape.wiki/images/Evil_Bob.png?e6922',
    alt: 'Evil Bob',
    description:
      'You are a creative, intelligent creature, with a great sense of humor, but you are also stubborn and impulsive. Your mind is a bit twisted and you see the world a little different than everyone around you.',
    traits: [
      'intelligence',
      'humor',
      'gamer',
      'power hungry',
      'impuulsive',
      'stubborn',
      'greedy',
      'creative',
    ],
    score: 0,
  },
  {
    id: 2,
    charName: 'Evil Dave',
    picture: 'https://oldschool.runescape.wiki/images/Evil_Dave.png?1d687',
    alt: 'Evil Dave',
    description:
      "You probably live in your mother's basement! Even though you are an intelligent, persuasive, and powerful creature, you often find yourself being careless and greedy.",
    traits: [
      'intelligence',
      'powerful',
      'gamer',
      'power hungry',
      'persuasive',
      'leader',
      'impulsive',
      'stubborn',
      'careless',
      'greedy',
    ],
    score: 0,
  },
  {
    id: 3,
    charName: 'Dad',
    picture:
      'https://oldschool.runescape.wiki/images/thumb/Dad.png/800px-Dad.png?18a30',
    alt: 'Dad',
    description:
      'One of the most powerful and courageous of your kind! You are loyal to your fellow companions and show great leadership. You may be stubborn at times.',
    traits: [
      'loyal',
      'powerful',
      'courage',
      'self-reliant',
      'stubborn',
      'careless',
      'greedy',
    ],
    score: 0,
  },
  {
    id: 4,
    charName: 'Hazelmere',
    picture: 'https://oldschool.runescape.wiki/images/Hazelmere.png?4d1ce',
    alt: 'Hazelmere',
    description:
      'You are one of the best of your kind! You are loyal, honest, intelligent, funny, empathetic... and I could go on! Your kind has leaned on you in the past and you always come through! The world of Gilenor is better with you in it!',
    traits: [
      'loyal',
      'honest',
      'intelligence',
      'powerful',
      'humor',
      'gamer',
      'empathy',
      'responsible',
      'courage',
      'outspoken',
      'creative',
      'kind',
    ],
    score: 0,
  },
  {
    id: 5,
    charName: 'Goblin',
    picture:
      'https://oldschool.runescape.wiki/images/thumb/Goblin.png/800px-Goblin.png?3e49a',
    alt: 'Goblin',
    description:
      'There are lots of you in this world... probably too many. You are loyal to what you believe in and always show courage. You can be careless and greedy at times, but you always do what you believe is best.',
    traits: [
      'loyal',
      'courage',
      'impulsive',
      'predictable',
      'stubborn',
      'careless',
      'greedy',
    ],
    score: 0,
  },
  {
    id: 6,
    charName: 'King Black Dragon',
    picture:
      'https://oldschool.runescape.wiki/images/King_Black_Dragon.png?d25f0',
    alt: 'King Black Dragon',
    description:
      'You have existed since before the first age. Even though you were a failed experiment, you turned into one of the most powerful and feared creatures! Your three heads and split personalities do not stop you.',
    traits: [
      'powerful',
      'gamer',
      'power hungry',
      'powerful',
      'courage',
      'impulsive',
      'self-reliant',
      'predictable',
      'stubborn',
      'careless',
    ],
    score: 0,
  },
  {
    id: 7,
    charName: 'Baby Mole',
    picture:
      'https://oldschool.runescape.wiki/images/Baby_Mole_%28follower%29.png?c4d59',
    alt: 'Baby Mole',
    description:
      'A very cute and lovable one you are. One of the most sought after creatures in all of Gilenor. You have a fun and loving personality that shines even though you choose to spend most of your time out of the sunlight.',
    traits: [
      'gamer',
      'honest',
      'loyal',
      'impulsive',
      'courage',
      'impulsive',
      'outspoken',
      'creative',
      'kind',
    ],
    score: 0,
  },
  {
    id: 8,
    charName: 'White Knight',
    picture:
      'https://oldschool.runescape.wiki/images/thumb/White_Knight.png/320px-White_Knight.png?8b8e4',
    alt: 'White Knight',
    description:
      'You are a brave warrior! While not being one of the strongest in Gilenor, you give it your all and fight for your kingdom. Anyone would be lucky to have you by their side. Your loyalty, courage, and kindness is valued.',
    traits: [
      'loyal',
      'honest',
      'loyal',
      'empathy',
      'courage',
      'leader',
      'courage',
      'responsible',
      'self-reliant',
      'predictable',
      'kind',
    ],
    score: 0,
  },
  {
    id: 9,
    charName: 'Gertrude',
    picture:
      'https://oldschool.runescape.wiki/images/thumb/Gertrude.png/320px-Gertrude.png?70a1b',
    alt: 'Gertrude',
    description:
      'Well known as the cat lady. Even though you and your home are kinda smelly, you are a very loving person and everyone can appreciate that! The world of Gilenor is a greater place because of you!',
    traits: [
      'loyal',
      'honest',
      'empathy',
      'empathy',
      'responsible',
      'self-reliant',
      'stubborn',
      'kind',
      'creative',
      'outspoken',
    ],
    score: 0,
  },
  {
    id: 10,
    charName: 'King Awowogei',
    picture: 'https://oldschool.runescape.wiki/images/Awowogei.png?0ea6b',
    alt: 'King Awowogei',
    description:
      'You are a very powerful creature! Your loyalty and intelligence is overwhelming. You can be very persuasive at times and that is part of what makes you a great leader. What a gamer!',
    traits: [
      'loyal',
      'honest',
      'intelligence',
      'powerful',
      'gamer',
      'power hungry',
      'empathy',
      'persuasive',
      'leader',
      'outspoken',
      'courage',
      'responsible',
      'stubborn',
      'careless',
      'greedy',
      'creative',
      'kind',
    ],
    score: 0,
  },
  {
    id: 11,
    charName: 'Vanescula Drakan',
    picture:
      'https://oldschool.runescape.wiki/images/Vanescula_Drakan.png?e78ba',
    alt: 'Vanescula Drakan',
    description:
      'You are an intrical part of an outsider society. You do your best to ensure the survival of your kind. Although many will see you as dark and evil at times, you are a great leader and do what you think is right.',
    traits: [
      'loyal',
      'honest',
      'intelligence',
      'powerful',
      'gamer',
      'power hungry',
      'empathy',
      'persuasive',
      'leader',
      'outspoken',
      'courage',
      'responsible',
      'stubborn',
      'careless',
      'greedy',
      'creative',
      'kind',
    ],
    score: 0,
  },
];

export default Characters;
